Eproject3/Models/Tips.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Eproject3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tips
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tips()
    {

        this.FeedBack = new HashSet<FeedBack>();

    }


    public int id { get; set; }

    public Nullable<int> Use_id { get; set; }

    public string Content { get; set; }

    public string Img { get; set; }

    public string Title { get; set; }

    public string Levels { get; set; }

    public Nullable<int> Cate_id { get; set; }

    public Nullable<bool> isFree { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FeedBack> FeedBack { get; set; }

    public virtual Users Users { get; set; }

    public virtual Categories Categories { get; set; }

}

}

Eproject3/Areas/Admin/Controllers/TipsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eproject3.Models;
using System.IO;

namespace Eproject3.Areas.Admin.Controllers
{
    public class TipsController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();

        // GET: Tips
        public async Task<ActionResult> Index()
        {
            if (Session["isAdmin"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var tips = db.Tips.Include(t => t.Users);
            return View(await tips.ToListAsync());
        }

        // GET: Tips/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tips tips = await db.Tips.FindAsync(id);
            if (tips == null)
            {
                return HttpNotFound();
            }
            return View(tips);
        }

        // GET: Tips/Create
        public ActionResult Create()
        {
            Users u = (Users)Session["User"];
            if (u != null)
            {
                ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                return View();
            }
            return Redirect("~/Users/LoginView");
        }

        // POST: Tips/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,Use_id,Content,Img,Title,Levels,Cate_id,isFree")] Tips tips, HttpPostedFileBase[] Url, string[] txtText, string rate)
        {
            int flag = 0;
            string Cont = "";
            string url_img = "";
            string[] formats = new string[] { ".jpg", ".png", ".gif", ".jpeg" };
            if (ModelState.IsValid)
            {
                try
                {
                    foreach (HttpPostedFileBase img in Url)
                    {
                        if (img != null)
                        {

                            string ex = Path.GetExtension(img.FileName);
                            if (!check(ex, formats))
                            {
                                flag = 1;
                                ViewBag.FileStatus = ex + " is not an image";
                                ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                                return View(tips);
                            }
                            url_img += Path.GetFileName(img.FileName) + "$";
                        }
                        else
                        {
                            flag = 1;
                            ViewBag.FileStatus = "Content must have image !!!!";
                            ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                            return View(tips);
                        }
                        if (flag != 1)
                        {
                            string path = Path.Combine(Server.MapPath("~/images"), Path.GetFileName(img.FileName));
                            img.SaveAs(path);
                        }
                    }
                }
                catch (Exception e)
                {
                    ViewBag.FileStatus = "Error while file uploading.";
                }

                tips.Img = url_img.Substring(0, url_img.Length - 1);

                foreach (var text in txtText)
                {
                    if (text != "")
                    {

                        Cont += text + "$";
                    }
                }
                Cont = Cont.Substring(0, Cont.Length - 1);
                tips.Content = Cont;
                var isvalid = (Users)Session["user"];
                if (isvalid == null) {
                    return RedirectToAction("LoginView", "Users");
                }
                tips.Use_id = isvalid.id;
                
                if (flag != 1)
                {
                    tips.Levels = rate;
                    db.Tips.Add(tips);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                    return View(tips);
                }
            }

            ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
            return View(tips);
        }

        // GET: Tips/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (Session["isAdmin"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tips tips = await db.Tips.FindAsync(id);
            if (tips == null)
            {
                return HttpNotFound();
            }
            ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
            return View(tips);
        }

        // POST: Tips/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,Use_id,Content,Img,Title,Levels,Cate_id,isFree")] Tips tips, HttpPostedFileBase[] Url, string[] txtText, int Free, string rate)
        {
            int flag = 0;
            string Cont = "";
            string url_img = "";
            string[] formats = new string[] { ".jpg", ".png", ".gif", ".jpeg" };
            if (ModelState.IsValid)
            {
                try
                {
                    foreach (HttpPostedFileBase img in Url)
                    {
                        if (img != null)
                        {

                            string ex = Path.GetExtension(img.FileName);
                            if (!check(ex, formats))
                            {
                                flag = 1;
                                ViewBag.FileStatus = ex + " is not an image";
                                ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                                return View(tips);
                            }
                            url_img += Path.GetFileName(img.FileName) + "$";
                        }
                        else
                        {
                            flag = 1;
                            ViewBag.FileStatus = "Content must have image !!!!";
                            ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                            return View(tips);
                        }
                        if (flag != 1)
                        {
                            string path = Path.Combine(Server.MapPath("~/images"), Path.GetFileName(img.FileName));
                            img.SaveAs(path);
                        }
                    }
                }
                catch (Exception e)
                {
                    ViewBag.FileStatus = "Error while file uploading.";
                }

                tips.Img = url_img.Substring(0, url_img.Length - 1);

                foreach (var text in txtText)
                {
                    if (text != "")
                    {

                        Cont += text + "$";
                    }
                }
                Cont = Cont.Substring(0, Cont.Length - 1);
                tips.Content = Cont;
                var isvalid = (Users)Session["user"];
                if (isvalid == null)
                {
                    return RedirectToAction("LoginView", "Users");
                }
                tips.Use_id = isvalid.id;
                if (Free == 0)
                {
                    tips.isFree = true;
                }
                else
                {
                    tips.isFree = false;
                }
                if (flag != 1)
                {
                    tips.Levels = rate;
                    db.Entry(tips).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else {
                    ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                    return View(tips);
                }
            }
            //ViewBag.Use_id = new SelectList(db.Users, "id", "UPhone", tips.Use_id);
            ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
            return View(tips);
        }

        // GET: Tips/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (Session["isAdmin"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tips tips = await db.Tips.FindAsync(id);
            if (tips == null)
            {
                return HttpNotFound();
            }
            return View(tips);
        }

        // POST: Tips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

Eproject3/Areas/Admin/Views/Tips/Create.cshtml
@model Eproject3.Models.Tips

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Rate.css">
<h2>Create</h2>


@using (Html.BeginForm("Create", "Tips", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create new Tips</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p id="cont">
                    <input type="text" id="content" name="txtText" required />
                    <input type="file" name="Url" />
                </p>
                <button id="addContent" type="button" class="btn btn-outline-primary btn-lg">+</button>
                <button id="RemoveContent" type="button" class="btn btn-outline-primary btn-lg">-</button>
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.isFree, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.isFree, new SelectList(new[] { new { Value = "true", Text = "Free" }, new { Value = "false", Text = "Must be member for read" }, }, "Value", "Text", Model))
                @Html.ValidationMessageFor(model => model.isFree, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Cate_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cate_id", (IEnumerable<SelectListItem>) ViewBag.Cate_id, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cate_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Levels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="rate">
                    <input type="radio" id="star5" name="rate" value="5" />
                    <label for="star5" title="very hard">5 stars</label>
                    <input type="radio" id="star4" name="rate" value="4" />
                    <label for="star4" title="hard">4 stars</label>
                    <input type="radio" id="star3" name="rate" value="3" />
                    <label for="star3" title="medium">3 stars</label>
                    <input type="radio" id="star2" name="rate" value="2" />
                    <label for="star2" title="easy">2 stars</label>
                    <input type="radio" id="star1" name="rate" value="1" />
                    <label for="star1" title="for children">1 star</label>
                </div>
                @Html.ValidationMessageFor(model => model.Levels, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <p style="color:red;">@ViewBag.FileStatus</p>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>

    $("#addContent").click(function e() {
            $("<p id=\"cont\"> <input type=\"text\" id=\"content\" name=\"txtText\" required />"+" <input type=\"file\" name=\"Url\" /></p>").insertBefore("#addContent");
    });
    $("#RemoveContent").click(function e() {
        $("#RemoveContent").prev().prev().remove();
    });

</script>

Eproject3/Areas/Admin/Views/Tips/Delete.cshtml
@model Eproject3.Models.Tips

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tips</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Users.UPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Users.UPhone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Eproject3/Areas/Admin/Views/Tips/Details.cshtml
@model Eproject3.Models.Tips
@using Eproject3.Models;
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Users u = new Users();
    if (Session["user"] != null)
    {
        u = (Users)Session["user"];
    }
}
<style>
    .checked {
        color: orange;
    }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="col-sm-12" id="detail-background">
    <div class="col-sm-2"></div>

    <div class="col-sm-8 content-detail">
        <div class="col-sm-12">
            <div class="col-sm-2">
                <div class="user-icon">
                    <img src="~/images/@Model.Users.Img" alt="Avatar" height="50" width="50" />
                </div>
            </div>
            <div class="col-sm-10 title">
                <i><b>@Html.DisplayFor(@model => @model.Title)</b></i>
            </div>
        </div>
        <hr />
        <hr>
        <div class="col-sm-12 blog-content-detail">
            <div class="col-sm-12">
                <h3>How to do</h3>
                <div class="col-sm-12">
                    @{
                        var Content_step = Model.Content.Split('$').ToList();
                        var ImgList = Model.Img.Split('$').ToList();
                        int i = 0;
                        foreach (var image in ImgList)
                        {
                            i++;
                            <div class="col-sm-12">
                                <p>Step @i: @Content_step.ElementAt(i - 1)</p>
                            </div>
                            <div class="center-content"> <img src="~/images/@image" alt="Food" /> </div>

                        }
                    }
                </div>
            </div>
        </div>
        <hr />
        <div class="blog-img">
            <div class="col-sm-12 blog-content-detail">
                <div class="col-sm-12">
                    <h3>Level</h3>
                    @{
                        for (int index = 0; index < 5; index++)
                        {
                            if (index < Convert.ToInt32(Model.Levels))
                            {
                                <span class="fa fa-star checked" id="rate"></span>
                            }
                            else
                            {
                                <span class="fa fa-star" id="rate"></span>
                            }
                        }
                    }
                </div>
            </div>
            <div class="col-sm-12 bar">
                <div class="col-sm-12">
                    <div class="col-sm-6">
                        FeedBack
                    </div>
                </div>
            </div>
            <br />
            <div class="col-sm-12 feedback-content">
                @if (Session["user"] != null)
                {
                    <div class="col-sm-2">
                        <div class="user-icon-feedback">
                            <img src="~/images/@u.Img" alt="Avatar" />
                        </div>
                    </div>
                    <div class="col-sm-10 comment">
                        <div class="col-sm-8 send-feedback">
                            @u.UAdress
                            @Html.AntiForgeryToken()
                            <input type="text" id="yourFeedback" name="Content" autocomplete="off" placeholder="Enter feedback" onkeypress="sendFeedback(event, 'yourFeedback')" />
                        </div>
                        <div class="col-sm-2">
                            <button onclick="sendFeedbackWithClick('yourFeedback')">Send</button>
                        </div>
                    </div>
                }
                else
                {
                    <a href="/Tips/LoginToComment/@Model.id">Login to Comment</a>
                }

            </div>
            @foreach (var item in ViewBag.FeedBack)
            {                
                <div class="col-sm-12 feedback-content">
                    <div class="col-sm-2">
                        <div class="user-icon-feedback">
                            <img src="~/images/@item.Users.Img" alt="Avatar" />
                        </div>
                    </div>
                    <div class="col-sm-9 comment">
                        <strong>@item.Users.UAdress</strong><br />
                        <i>@item.Content</i>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@{
    if (u != null)
    {
        <script>
            async function sendFeedback(event, id) {

                if (event.keyCode == 13) {
                    sendFeedbackWithClick(id);
                }
            }
            async function sendFeedbackWithClick(id) {
                var xhr = new XMLHttpRequest();
                xhr.open("POST", "../../FeedBacks/CreateTips", true);
                xhr.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');
                @*
                            alert( JSON.stringify({
                                "Use_id": @u.id.ToString(),
                                "Recipes_id": @Model.id.ToString(),
                                "Content": document.getElementById(id).value
                            }))
                                 *@
                try{
                    await xhr.send(
                    JSON.stringify({
                        "Use_id":  @u.id.ToString(),
                        "Tip_id": @Model.id.ToString(),
                        "Content": document.getElementById(id).value,
                        "__RequestVerificationToken": document.getElementsByName("__RequestVerificationToken").value
                    })

                 );

                } catch(e){

                }


                setTimeout(function(){
                    window.location.reload();
                },4000)


            }




        </script>
    }
    else
    {
        <script>
            function sendFeedback(event, id) {

                if (event.keyCode == 13) {
                    sendFeedbackWithClick(id);
                }
            }

            function sendFeedbackWithClick(id) {
                alert("điều hướng trang");
                this.goto('../../Users/LoginView');
            }

        </script>
    }

}

<div class="col-sm-2"></div>

Eproject3/Areas/Admin/Views/Tips/Edit.cshtml
@model Eproject3.Models.Tips

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tips</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    var Content_step = Model.Content.Split(',').ToList();
                    foreach (var i in Content_step)
                    {
                        <p>  <input type="text" name="txtText" value="@i" class="form-control" required /> <input type="file" name="Url" class="form-control" /></p>
                    }
                    <button id="addContent" type="button" class="btn btn-outline-primary btn-lg">+</button>
                    <button id="RemoveContent" type="button" class="btn btn-outline-primary btn-lg">-</button>
                }

                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.isFree, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.isFree, new SelectList(new[] { new { Value = "true", Text = "Free" }, new { Value = "false", Text = "Must be member for read" }, }, "Value", "Text", Model))
                @Html.ValidationMessageFor(model => model.isFree, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Cate_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cate_id", (IEnumerable<SelectListItem>)ViewBag.Cate_id, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cate_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Levels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="rate">
                    <input type="radio" id="star5" name="rate" value="5" />
                    <label for="star5" title="very hard">5 stars</label>
                    <input type="radio" id="star4" name="rate" value="4" />
                    <label for="star4" title="hard">4 stars</label>
                    <input type="radio" id="star3" name="rate" value="3" />
                    <label for="star3" title="medium">3 stars</label>
                    <input type="radio" id="star2" name="rate" value="2" />
                    <label for="star2" title="easy">2 stars</label>
                    <input type="radio" id="star1" name="rate" value="1" />
                    <label for="star1" title="for children">1 star</label>
                </div>
                @Html.ValidationMessageFor(model => model.Levels, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                <p style="color:red;">@ViewBag.FileStatus</p>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>
    $(document).ready(function () {
        var Level = @Model.Levels;
        console.log(Level)
        $("input[type=radio]").each(function () {
            if ($(this).val() == Level) {
                this.setAttribute("checked", "checked");
            }

        });


    });
    $("#addContent").click(function e() {
            $(" <p>"+" <input type=\"text\" id=\"content\" name=\"txtText\" class=\"form-control\"/>"+" <input type=\"file\" name=\"Url\"class=\"form-control\" />"+ "</p>").insertBefore("#addContent");
    });
    $("#RemoveContent").click(function e() {
        $("#RemoveContent").prev().prev().remove();
    });
</script>