Eproject3/Models/Contest.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Eproject3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Contest
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Contest()
    {

        this.Exams = new HashSet<Exams>();

        this.Contester = new HashSet<Contester>();

    }


    public int id { get; set; }

    public Nullable<System.DateTime> C_Time { get; set; }

    public Nullable<System.DateTime> exp_time { get; set; }

    public string C_Description { get; set; }

    public string img { get; set; }

    public Nullable<int> id_winner { get; set; }

    public string title { get; set; }

    public string requirement { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Exams> Exams { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Contester> Contester { get; set; }

    public virtual Contester Contester1 { get; set; }

}

}

Eproject3/Areas/Admin/Controllers/ContestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eproject3.Models;
using System.IO;

namespace Eproject3.Areas.Admin.Controllers
{
    public class ContestsController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();

        // GET: Contests
        public async Task<ActionResult> Index()
        {
            if (Session["isAdmin"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View(await db.Contest.OrderByDescending(p=>p.id).ToListAsync());
        }

        // GET: Contests/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = await db.Contest.FindAsync(id);
            if (contest == null)
            {                
                return HttpNotFound();
            }
            return View(contest);
        }

        // GET: Contests/Create
        public ActionResult Create()
        {
            if (Session["isAdmin"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        // POST: Contests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,title,requirement,C_Time,exp_time,C_Description,img")] Contest contest, HttpPostedFileBase Url)
        {
            if (DateTime.Compare(contest.C_Time.Value,contest.exp_time.Value) >0)
            {
                ViewBag.Soon = "Start date can not be later than end date ";
                return View(contest);
            }
            string url_img = "";
            if (ModelState.IsValid)
            {
                try
                {
                    string path = Path.Combine(Server.MapPath("~/images"), Path.GetFileName(Url.FileName));
                    Url.SaveAs(path);
                    url_img += Path.GetFileName(Url.FileName) + ",";
                }
                catch (Exception e)
                {
                    ViewBag.FileStatus = "Error while file uploading.";
                }
                contest.img = url_img.Substring(0, url_img.Length - 1);
                db.Contest.Add(contest);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(contest);
        }

        // GET: Contests/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (Session["isAdmin"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = await db.Contest.FindAsync(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            return View(contest);
        }

        // POST: Contests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,title,requirement,C_Time,exp_time,C_Description,img,id_winner")] Contest contest, HttpPostedFileBase Url)
        {
            if (DateTime.Compare(contest.C_Time.Value, contest.exp_time.Value) > 0)
            {
                
                ViewBag.Soon = "Start date can not be earlier than end date ";
                return View(contest);
            }
            if (ModelState.IsValid)
            {
                string url_img = "";
                try
                {
                    string path = Path.Combine(Server.MapPath("~/images"), Path.GetFileName(Url.FileName));
                    Url.SaveAs(path);
                    url_img += Path.GetFileName(Url.FileName) + ",";
                }
                catch (Exception e)
                {
                    ViewBag.FileStatus = "Error while file uploading.";
                }
                if (Url != null)
                {
                    contest.img = url_img.Substring(0, url_img.Length - 1);
                }
                db.Entry(contest).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(contest);
        }

        // GET: Contests/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (Session["isAdmin"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (TempData["cas"] != null)
            {
                ViewBag.cas = "There are contestants in this contest,can not drop";
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = await db.Contest.FindAsync(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            return View(contest);
        }

        // POST: Contests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (db.Contester.Where(p=>p.Contest_id==id).Count() >0)
            {
                TempData["cas"] = true;
                return RedirectToAction("Delete/"+id);
            }
            Contest contest = await db.Contest.FindAsync(id);
            db.Contest.Remove(contest);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> ForceDelete(int id)
        {
            db.Exams.ToList().RemoveAll(p=>p.Contest_id==id);
            db.Contester.ToList().RemoveAll(p=>p.Contest_id==id);
            Contest contest = await db.Contest.FindAsync(id);
            db.Contest.Remove(contest);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Eproject3/Controllers/ContestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eproject3.Models;
using PagedList;
namespace Eproject3.Controllers
{
    public class ContestsController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();

        // GET: Contests
        public ActionResult Index(int? page)
        {
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            DateTime next7days = DateTime.Today.AddDays(7);
            var contest = db.Contest.OrderByDescending(p => p.id).ToList();
            return View(contest.ToPagedList(pageNumber, pageSize));
        }

        // GET: Contests/Details/5
        public async Task<ActionResult> Details(int? id,int? page)
        {
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            ViewBag.exams = db.Exams.Where(p=>p.Contest_id==id).OrderByDescending(p=>p.Mark).ToList().ToPagedList(pageNumber,pageSize);
            if (TempData["over"] != null)
            {
                ViewBag.over = TempData["over"];
            }
            if (TempData["early"] != null)
            {
                ViewBag.early = TempData["early"];
            }
            if (TempData["exist"] != null)
            {
                ViewBag.exist = TempData["exist"];
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = await db.Contest.FindAsync(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            return View(contest);
        }
        public ActionResult Join(int id)
        {
            var isvalid = db.Contest.Find(id);
            if (isvalid.exp_time<DateTime.Now)
            {
                TempData["over"] = "This contest is over";
                return RedirectToAction("Details/" + id);
            }else if (isvalid.C_Time>DateTime.Now)
            {
                TempData["early"] = "This contest has not begun yet";
                return RedirectToAction("Details/" + id);
            }
            TempData["ctId"] = id;           
            return RedirectToAction("Create","Contesters");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Eproject3/Areas/Admin/Views/Contests/Create.cshtml
@model Eproject3.Models.Contest

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@ViewBag.Soon
@using (Html.BeginForm("Create", "Contests", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add new Contests</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.C_Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.C_Time, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.C_Time, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.C_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.C_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.C_Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.requirement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.requirement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.requirement, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="url" />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.exp_time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.exp_time, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.exp_time, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Eproject3/Areas/Admin/Views/Contests/Delete.cshtml
@model Eproject3.Models.Contest

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contest</h4>
    @if (ViewBag.cas != null)
    {
        <h5 style="color:red">@ViewBag.cas </h5>
        <a style="color:red" href="/Admin/Contests/ForceDelete/@Model.id">Force Delete</a>
    }
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.C_Time)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.C_Time)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.C_Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.C_Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.exp_time)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.exp_time)
        </dd>
        <dt>
            images
        </dt>
        <dd>
            <img style="width:200px;height:180px" src="~/images/@Html.DisplayFor(model => model.img)" />
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Eproject3/Areas/Admin/Views/Contests/Edit.cshtml
@model Eproject3.Models.Contest
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>
@ViewBag.Soon

@using (Html.BeginForm("Edit", "Contests", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Contest</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)
    @Html.EditorFor(model=>model.id_winner)
    @Html.EditorFor(model=>model.Contester1)
    <div class="form-group">
        @Html.LabelFor(model => model.C_Time, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.C_Time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.C_Time, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.requirement, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.requirement, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.requirement, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.C_Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.C_Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.C_Description, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="url" />
        </div>
    </div>
    @Html.HiddenFor(model => model.img)
    <div class="form-group">
        @Html.LabelFor(model => model.exp_time, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.exp_time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.exp_time, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Eproject3/Areas/Admin/Views/Contests/Index.cshtml
@Styles.Render("~/Content/content/bootstrap.min.css")
@Styles.Render("~/Content/content/light-bootstrap-dashboard.css")
@Styles.Render("~/Content/content/demo.css")
@model IEnumerable<Eproject3.Models.Contest>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Contests</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link href="../assets/content/bootstrap.min.css" rel="stylesheet" />
    <link href="../assets/content/light-bootstrap-dashboard.css?v=2.0.0 " rel="stylesheet" />
    <link href="../assets/content/demo.css" rel="stylesheet" />
</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-image="../assets/img/sidebar-5.jpg">
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="/Home/" class="simple-text">
                        James Theme's Culinary blog
                    </a>
                </div>
                <ul class="nav">
                    <li>
                        <a class="nav-link" href="/Admin/Home/">
                            <i class="nc-icon nc-circle-09"></i>
                            <p>User Profile</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="/Admin/Recipes">
                            <i class="nc-icon nc-paper-2"></i>
                            <p>Recipes</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="/Admin/Categories">
                            <i class="nc-icon nc-bullet-list-67"></i>
                            <p>Category</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="/Admin/Tips">
                            <i class="nc-icon nc-notes"></i>
                            <p>Tips</p>
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/Admin/Contests">
                            <i class="nc-icon nc-air-baloon"></i>
                            <p>Contest</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="/Admin/Users">
                            <i class="nc-icon nc-badge"></i>
                            <p>Users</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#pablo"> User </a>

                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="nav navbar-nav mr-auto">
                            <li class="dropdown nav-item">
                                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                    <span class="notification">Private task</span>
                                    <span class="d-lg-none">Notification</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <a class="dropdown-item" href="/Admin/Users/ChangePwd">Change password</a>
                                    <a class="dropdown-item" href="/Admin/Users/ChangePhoto">Change profile picture</a>
                                </ul>
                            </li>
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="/Home/">
                                    <span class="no-icon">Home</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/Admin/Users/LogOut">
                                    <span class="no-icon">Log out</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            @*Code*@
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card strpied-tabled-with-hover">
                                <div class="card-header ">
                                    <h4 class="card-title">Contests List</h4>
                                </div>
                                <div class="card-header ">
                                    <h6 class="card-title">@Html.ActionLink("Create New", "Create")</h6>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                    <table id="myTable" class="table table-hover table-striped">
                                        <thead>
                                            <tr>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.title)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.C_Time)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.exp_time)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.C_Description)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.requirement)
                                                </th>
                                                <th>
                                                    Image
                                                </th>
                                                <th>
                                                    Number of Exams/Marking
                                                </th>
                                                <th>
                                                    Winner
                                                </th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.title)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.C_Time)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.exp_time)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.C_Description)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.requirement)
                                                    </td>
                                                    <th>
                                                        <img src="~/images/@item.img" style="height:50px;width:50px" />
                                                    </th>
                                                    <td>
                                                        <a href="/Admin/Contesters/Contesters/@item.id">
                                                            @item.Contester.Count()
                                                        </a>
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Contester1.Name)
                                                    </td>
                                                    <td>
                                                        @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                                                        @Html.ActionLink("Delete", "Delete", new { id = item.id })
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<script src="../Content/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="../Content/js/core/popper.min.js" type="text/javascript"></script>
<script src="../Content/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="../Content/js/plugins/bootstrap-switch.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<script src="../Content/js/plugins/chartist.min.js"></script>
<script src="../Content/js/plugins/bootstrap-notify.js"></script>
<script src="../Content/js/light-bootstrap-dashboard.js?v=2.0.0 " type="text/javascript"></script>
<script src="../Content/js/demo.js"></script>
</html>

<link href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>