Eproject3/Models/Recipes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Eproject3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Recipes
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Recipes()
    {

        this.Exams = new HashSet<Exams>();

        this.FeedBack = new HashSet<FeedBack>();

    }


    public int id { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Img { get; set; }

    public Nullable<int> Contester_id { get; set; }

    public Nullable<int> R_Status { get; set; }

    public string ingredent { get; set; }

    public string Levels { get; set; }

    public Nullable<int> Cate_id { get; set; }



    public virtual Contester Contester { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Exams> Exams { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FeedBack> FeedBack { get; set; }

    public virtual Users Users { get; set; }

    public virtual Categories Categories { get; set; }

}

}

Eproject3/Areas/Admin/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eproject3.Models;
using System.IO;

namespace Eproject3.Areas.Admin.Controllers
{
    public class RecipesController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();

        // GET: Recipes
        public async Task<ActionResult> Index()
        {
            if (Session["isAdmin"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var recipes = db.Recipes.Include(r => r.Users);
            return View(await recipes.ToListAsync());
        }
        // GET: Recipes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Lay feedbacks
            ViewBag.FeedBack = db.FeedBack.Where(m => m.Recipes_id == id).Include(i => i.Users).ToList();
            Recipes recipes = await db.Recipes.FindAsync(id);
            if (recipes == null)
            {
                return HttpNotFound();
            }
            return View(recipes);
        }
        /// <summary>
        /// phan cu hai
        /// </summary>
        /// <returns></returns>
        // GET: Recipes/Create
        public ActionResult Create()
        {
            Users u = (Users)Session["User"];
            if (u != null)
            {
                ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                return View();
            }
            return RedirectToAction("LoginView", "Users");
        }

        // POST: Recipes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,Title,Content,Img,Contester_id,R_Status,Cate_id")] Recipes recipes, HttpPostedFileBase[] Url, string[] txtText, string[] txtIgredent, int txtStatus, string rate)
        {
            int flag = 0;
            string Cont = "";
            string url_img = "";
            string ingre = "";
            string[] formats = new string[] { ".jpg", ".png", ".gif", ".jpeg" };
            if (ModelState.IsValid)
            {
                try
                {
                    foreach (HttpPostedFileBase img in Url)
                    {
                        if (img != null)
                        {

                            string ex = Path.GetExtension(img.FileName);
                            if (!check(ex, formats))
                            {
                                flag = 1;
                                ViewBag.FileStatus = ex + " is not an image";
                                ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                                return View(recipes);
                            }
                            url_img += Path.GetFileName(img.FileName) + "$";
                        }
                        else
                        {
                            flag = 1;
                            ViewBag.FileStatus = "Content must have image !!!!";
                            ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                            return View(recipes);

                        }
                        if (flag != 1)
                        {
                            string path = Path.Combine(Server.MapPath("~/images"), Path.GetFileName(img.FileName));
                            img.SaveAs(path);
                        }
                    }
                }
                catch (Exception e)
                {
                    ViewBag.FileStatus = "Error while file uploading.";
                }

                recipes.Img = url_img.Substring(0, url_img.Length - 1);

                foreach (var text in txtText)
                {
                    if (text != "")
                    {

                        Cont += text + "$";
                    }
                }
                foreach (var ingredent in txtIgredent)
                {
                    if (ingredent != "")
                    {

                        ingre += ingredent + "$";
                    }
                }
                Cont = Cont.Substring(0, Cont.Length - 1);
                recipes.Content = Cont;
                recipes.ingredent = ingre.Substring(0, ingre.Length - 1);
                if (Session["user"] != null)
                {
                    var isvalid = (Users)Session["user"];
                    recipes.Contester_id = isvalid.id;
                }
                else
                {
                    recipes.Contester_id = db.Users.Where(p => p.UPhone == "000").FirstOrDefault().id;
                }
                if (flag != 1)
                {
                    recipes.Levels = rate;
                    recipes.R_Status = txtStatus;
                    db.Recipes.Add(recipes);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else {
                    ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                    return View(recipes);
                }               
            }
            ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
            return View(recipes);
        }
        // GET: Recipes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (Session["isAdmin"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipes recipes = await db.Recipes.FindAsync(id);
            if (recipes == null)
            {
                return HttpNotFound();
            }
            ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
            return View(recipes);
        }

        // POST: Recipes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,Title,Content,Img,Contester_id,R_Status,Cate_id")] Recipes recipes, HttpPostedFileBase[] Url, string[] txtText, string[] txtIgredent, int txtStatus, string rate)
        {
            int flag = 0;
            string Cont = "";
            string url_img = "";
            string ingre = "";
            string[] formats = new string[] { ".jpg", ".png", ".gif", ".jpeg" };
            if (ModelState.IsValid)
            {
                try
                {
                    foreach (HttpPostedFileBase img in Url)
                    {
                        if (img != null)
                        {
                           
                            string ex = Path.GetExtension(img.FileName);
                            if (!check(ex, formats))
                            {
                                flag = 1;
                                ViewBag.FileStatus = ex + " is not an image";
                                ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                                return View(recipes);
                            }
                            url_img += Path.GetFileName(img.FileName) + "$";
                            recipes.Img = url_img.Substring(0, url_img.Length - 1);
                        }
                        if (flag != 1)
                        {
                            string path = Path.Combine(Server.MapPath("~/images"), Path.GetFileName(img.FileName));
                            img.SaveAs(path);
                        }
                    }


                }
                catch (Exception e)
                {
                    ViewBag.FileStatus = "Error while file uploading.";
                }


                foreach (var text in txtText)
                {
                    if (text != "")
                    {

                        Cont += text + "$";
                    }
                }
                foreach (var ingredent in txtIgredent)
                {
                    if (ingredent != "")
                    {

                        ingre += ingredent + "$";
                    }
                }
                if (Session["user"] != null)
                {
                    var isvalid = (Users)Session["user"];
                    recipes.Contester_id = isvalid.id;
                }
                if (flag != 1)
                {
                    recipes.Levels = rate;
                    Cont = Cont.Substring(0, Cont.Length - 1);
                    recipes.Content = Cont;
                    recipes.ingredent = ingre.Substring(0, ingre.Length - 1);
                    recipes.R_Status = txtStatus;
                    db.Entry(recipes).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else {
                    ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
                    return View(recipes);
                }
            }
            ViewBag.Cate_id = new SelectList(db.Categories.ToList(), "id", "Cate_name");
            return View(recipes);
        }

Eproject3/Areas/Admin/Views/Recipes/Create.cshtml
@model Eproject3.Models.Recipes

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Rate.css">
@using (Html.BeginForm("Create", "Recipes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @if (Session["Contest_id"] != null)
        {
            <h4>Recipes of @Session["Contest_id"].ToString()</h4>
            <input type="hidden" name="Contester_id" value="@Session["Contest_id"]" />
        }
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ingredent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p id="cont">
                    <input type="text" id="igre" name="txtIgredent" />
                </p>
                <button id="addIgre" type="button" class="btn btn-outline-primary btn-lg">+</button>
                <button id="RemoveIgre" type="button" class="btn btn-outline-primary btn-lg">-</button>
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p id="cont">
                    <input type="text" id="content" name="txtText" required />
                    <input type="file" name="Url" />
                </p>
                <button id="addContent" type="button" class="btn btn-outline-primary btn-lg">+</button>
                <button id="RemoveContent" type="button" class="btn btn-outline-primary btn-lg">-</button>
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.R_Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="txtStatus">
                    <option value="0">Free</option>
                    <option value="1">Only members can read this recipe</option>
                </select>
                @Html.ValidationMessageFor(model => model.R_Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Cate_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cate_id", (IEnumerable<SelectListItem>)ViewBag.Cate_id, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cate_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Levels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="rate">
                    <input type="radio" id="star5" name="rate" value="5" />
                    <label for="star5" title="very hard">5 stars</label>
                    <input type="radio" id="star4" name="rate" value="4" />
                    <label for="star4" title="hard">4 stars</label>
                    <input type="radio" id="star3" name="rate" value="3" />
                    <label for="star3" title="medium">3 stars</label>
                    <input type="radio" id="star2" name="rate" value="2" />
                    <label for="star2" title="easy">2 stars</label>
                    <input type="radio" id="star1" name="rate" value="1" />
                    <label for="star1" title="for children">1 star</label>
                </div>
                @Html.ValidationMessageFor(model => model.Levels, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <p style="color:red;">@ViewBag.FileStatus</p>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>

    $("#addContent").click(function e() {
        $("<p id=\"cont\"> <input type=\"text\" id=\"content\" name=\"txtText\" required />" + " <input type=\"file\" name=\"Url\" /></p>").insertBefore("#addContent");
    });
    $("#RemoveContent").click(function e() {
        $("#RemoveContent").prev().prev().remove();
    });
    $("#addIgre").click(function e() {
        $("<p id=\"igre\"> <input type=\"text\" id=\"content\" name=\"txtIgredent\" /></p>").insertBefore("#addIgre");
    });
    $("#RemoveIgre").click(function e() {
        $("#RemoveIgre").prev().prev().remove();
    });

</script>

Eproject3/Areas/Admin/Views/Recipes/Delete.cshtml
@model Eproject3.Models.Recipes

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.R_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.R_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contester.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contester.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Eproject3/Areas/Admin/Views/Recipes/Edit.cshtml
@model Eproject3.Models.Recipes

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var ingredent = Html.DisplayFor(model => model.ingredent).ToString();
    var content = Html.DisplayFor(model=>model.Content).ToString();
}

<h2>Edit</h2>
<link rel="stylesheet" type="text/css" href="~/Content/Rate.css">

@using (Html.BeginForm("Edit", "Recipes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Recipes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model=>model.Img)
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ingredent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @{
                    var Ingre_List = ingredent.Split(',').ToList();
                    foreach (var i in Ingre_List)
                    {

                        <input type="text" id="igre" name="txtIgredent" value="@i" class="form-control" autocomplete="off" required />
                    }
                    <button id="addIgre" type="button" class="btn btn-outline-primary btn-lg">+</button>
                    <button id="RemoveIgre" type="button" class="btn btn-outline-primary btn-lg">-</button>
                }
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Img, new { htmlAttributes = new { @class = "form-control", @type = "file" } })*@
                @{
                    var Content_step = content.Split(',').ToList();
                    foreach (var i in Content_step)
                    {
                        <p>  <input type="text" name="txtText" value="@i" class="form-control" autocomplete="off" required /> <input type="file" name="Url" class="form-control" /></p>
                    }
                    <button id="addContent" type="button" class="btn btn-outline-primary btn-lg">+</button>
                    <button id="RemoveContent" type="button" class="btn btn-outline-primary btn-lg">-</button>
                }

                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.R_Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="txtStatus">
                    <option value="0">Free</option>
                    <option value="1">Only members can read this recipe</option>
                </select>
                @Html.ValidationMessageFor(model => model.R_Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Cate_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cate_id", (IEnumerable<SelectListItem>)ViewBag.Cate_id, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cate_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Levels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="rate">
                    <input type="radio" id="star5" name="rate" value="5" />
                    <label for="star5" title="very hard">5 stars</label>
                    <input type="radio" id="star4" name="rate" value="4" />
                    <label for="star4" title="hard">4 stars</label>
                    <input type="radio" id="star3" name="rate" value="3" />
                    <label for="star3" title="medium">3 stars</label>
                    <input type="radio" id="star2" name="rate" value="2" />
                    <label for="star2" title="easy">2 stars</label>
                    <input type="radio" id="star1" name="rate" value="1" />

                    <label for="star1" title="for children">1 star</label>
                </div>
                @Html.ValidationMessageFor(model => model.R_Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                <p style="color:red;">@ViewBag.FileStatus</p>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>
    $(document).ready(function () {
        var Level = @Model.Levels;
        console.log(Level)
        $("input[type=radio]").each(function () {
            if ($(this).val() == Level) {
                this.setAttribute("checked", "checked");
            }

        });


    });
    $("#addContent").click(function e() {
            $(" <p>"+" <input type=\"text\" id=\"content\" name=\"txtText\" class=\"form-control\" autocomplete=\"off\" required/>"+" <input type=\"file\" name=\"Url\"class=\"form-control\" />"+ "</p>").insertBefore("#addContent");
    });
    $("#RemoveContent").click(function e() {
        $("#RemoveContent").prev().prev().remove();
    });
       $("#addIgre").click(function e() {
            $("<p id=\"igre\"> <input type=\"text\" id=\"content\" name=\"txtIgredent\" class=\"form-control\" autocomplete=\"off\" required/></p>").insertBefore("#addIgre");
    });
    $("#RemoveIgre").click(function e() {
        $("#RemoveIgre").prev().prev().remove();
    });
</script>